#!/bin/bash

[ -z "$1" ] && die "Project name not specified"
[ -z "$2" ] && die "Git source not specified"

name=$1
git_source=$2
full_path="$ART_ROOT/$name"

[ -d $full_path ] && die "Project '$name' already installed at '$full_path'"

git clone git@$git_source/$name.git "$full_path" 

[ -d "$full_path" ] || die "Project '$name' not installed"
