#!/bin/bash

echo "$ARTCLI_CONST_EXEC - CLI tool for art-ws.org ( See more details at https://github.com/art-ws/art-cli )
Version: $ARTCLI_CONST_VERSION
art <command/path> help - get <command/path> help 
 
Copyright (c) 2020 art-ws.org
License: https://www.apache.org/licenses/LICENSE-2.0
"
