#!/bin/bash

[ -z "$1" ] && die "Project name not specified"

full_path="$ART_ROOT/$1"
[ -d $full_path ] && die "Project '$1' already installed at '$full_path'"

git clone git@github.com:art-ws/$1.git "$full_path" 

[ -d "$full_path" ] || die "Project '$1' not installed"
