#!/bin/bash

main(){
  for project_name in `list_projects`
  do
    full_path=`lookup_path_at_project $project_name .`
    echo -e "\E[1;34m[$project_name]\E[0;37m - $(dirname $full_path)"
  done
}

main