#!/bin/bash

main(){
  local project_name=$1
  check_var project_name 
  
  local path=`lookup_path_at_project $project_name .`
  [ -z $path ] && die "Directory or link for project [ $project_name ] not found at $ART_REPO_ROOT"
 
  local tmp=`dirname $path`
  local dir_path=`dirname $tmp`
  local link_path=`readlink -f $dir_path`

  local type=""
  local suffix=""
  if [ $dir_path = $link_path  ] 
  then
    rm -fR $dir_path   
    type="directory"
  else
    rm $dir_path
    type="link"
    suffix=" ( $link_path ) "
  fi
  echo "Project [ $project_name ] $type $dir_path has been removed $suffix"
  return 0  
}

main $1