#!/bin/bash

main(){
  local name="$1"
  check_var name ARTCLI_VALUES_DIR

  if [ "$name" = "--all" ]; then
    [ -d "$ARTCLI_VALUES_DIR" ] && rm -fr "$ARTCLI_VALUES_DIR" 
  else
    local file_path="$ARTCLI_VALUES_DIR/$name"
    [ -f "$file_path" ] && rm "$file_path"
  fi
  
  return 0
}

main "$@"
