#!/bin/bash

main(){
  local action=$1
  check_var action
  
  shift 
  
  local path=`art a/actions/path $action`
  [ -z $path ] && die "Path for action '$action' not found"
  
  source $path $@
}

main $@